# Generated by Django 5.1.6 on 2025-03-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phonenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='authUser.customeuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.chatroom'),
        ),
    ]
